from mainRandomForest import *
import time

taux = time.time()
clf = RandomForest(n_trees=50, max_depth=5, min_samples_split=20)
clf.fit(X_train, y_train)
predictions = clf.predict(X_test)
print(f'A -> Accuracy: {accuracy_score(y_test, predictions)} | tempo: {time.time()-taux}')
taux = time.time()
clf = RandomForest(n_trees=200, max_depth=5, min_samples_split=20)
clf.fit(X_train, y_train)
predictions = clf.predict(X_test)
print(f'B -> Accuracy: {accuracy_score(y_test, predictions)} | tempo: {time.time()-taux}')
taux = time.time()
clf = RandomForest(n_trees=150, max_depth=7, min_samples_split=7)
clf.fit(X_train, y_train)
predictions = clf.predict(X_test)
print(f'C -> Accuracy: {accuracy_score(y_test, predictions)} | tempo: {time.time()-taux}')
taux = time.time()
clf = RandomForest(n_trees=100, max_depth=2, min_samples_split=2)
clf.fit(X_train, y_train)
predictions = clf.predict(X_test)
print(f'D -> Accuracy: {accuracy_score(y_test, predictions)} | tempo: {time.time()-taux}')
taux = time.time()
clf = RandomForest(n_trees=100, max_depth=10, min_samples_split=5)
clf.fit(X_train, y_train)
predictions = clf.predict(X_test)
print(f'E -> Accuracy: {accuracy_score(y_test, predictions)} | tempo: {time.time()-taux}')
taux = time.time()
