from mainC45 import *
import time

taux = time.time()

classifier = DecisionTreeClassifier(max_depth=2, min_samples_split=2, mode='gini')
classifier.fit(X_train,Y_train)
Y_pred = classifier.predict(X_test) 
print(f'A -> Accuracy: {accuracy_score(Y_test, Y_pred)} | tempo: {time.time()-taux}')
taux = time.time()
classifier = DecisionTreeClassifier(max_depth=10, min_samples_split=5, mode='gini')
classifier.fit(X_train,Y_train)
Y_pred = classifier.predict(X_test) 
print(f'B -> Accuracy: {accuracy_score(Y_test, Y_pred)} | tempo: {time.time()-taux}')
taux = time.time()
classifier = DecisionTreeClassifier(max_depth=5, min_samples_split=20, mode='gini')
classifier.fit(X_train,Y_train)
Y_pred = classifier.predict(X_test) 
print(f'C -> Accuracy: {accuracy_score(Y_test, Y_pred)} | tempo: {time.time()-taux}')
taux = time.time()
classifier = DecisionTreeClassifier(max_depth=2, min_samples_split=2, mode='entropy')
classifier.fit(X_train,Y_train)
Y_pred = classifier.predict(X_test) 
print(f'D -> Accuracy: {accuracy_score(Y_test, Y_pred)} | tempo: {time.time()-taux}')
taux = time.time()
classifier = DecisionTreeClassifier(max_depth=10, min_samples_split=5, mode='entropy')
classifier.fit(X_train,Y_train)
Y_pred = classifier.predict(X_test) 
print(f'E -> Accuracy: {accuracy_score(Y_test, Y_pred)} | tempo: {time.time()-taux}')